version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bookcatalog-postgres
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/booksdb-init.sql:/docker-entrypoint-initdb.d/booksdb-init.sql
    networks:
      - bookcatalog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookcatalog-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/booksdb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: secret
    networks:
      - bookcatalog-network

volumes:
  postgres_data:

networks:
  bookcatalog-network: