version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: bookcatalog-postgres
    environment:
     POSTGRES_DB: booksdb
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/booksdb-init.sql:/docker-entrypoint-initdb.d/booksdb-init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d booksdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - bookcatalog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookcatalog-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: azure
      SPRING_R2DBC_URL: r2dbc:postgresql://bookcatalog-pg-dev.postgres.database.azure.com:5432/booksdb?sslMode=require
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: Secret*01
      SPRING_FLYWAY_URL: jdbc:postgresql://bookcatalog-pg-dev.postgres.database.azure.com:5432/booksdb?sslMode=require
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: Secret*01
    networks:
      - bookcatalog-network

volumes:
  postgres_data:

networks:
  bookcatalog-network: